# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: hotstardl
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - 386
      - arm
# Archive customization
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: mac
